#!/usr/bin/env python3

import os
import pwd
import sys
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, HTTPServer


def _get_user_string() -> str:
    uid = os.geteuid()
    username = pwd.getpwuid(uid).pw_name
    return f"{username} ({uid})\n"


class HTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(HTTPStatus.OK)
        self.end_headers()
        self.wfile.write(_get_user_string().encode())


def run(port: int) -> None:
    print(f"Running on {port}")
    httpd = HTTPServer(('', port), HTTPRequestHandler)
    httpd.serve_forever()


if __name__ == "__main__":
    if len(sys.argv) == 2:
        port= int(sys.argv[1])
    else:
        port = 8000

    run(port)
